### ISSUE TITLE
Automatically begin countdown when code is executed

### ISSUE THREAD

**Issue by Dr-Joe-Roberts** [gadenbuie/countdown#12]
Would it be possible to incorporate an option for a countdown to begin automatically when using the countdown_fullscreen function?

I am writing code for an experiment where I have a function that uses the rstudio console to record user input, so it would be very useful to have a countdown displayed in the rstudio viewer!

**Comment by davidkane9** [comment]
I would also make use of this, although in a different context. I would like the countdown to start automatically, as soon as the xarigan slide appears. That is, I don't want to have to click on it manually.

**Comment by engineerchange** [comment]
+1 for this feature!
