### ISSUE TITLE
How to make it keep counting? (And a pause button)

### ISSUE THREAD

**Issue by moshpirit** [gadenbuie/countdown#13]
Hi! I'd like to make it keep counting after it reaches the 00:00, so 15 seconds later it would look like this: `-00:15` (in red and blinking) and a Pause button for a debating tournament if it's not asking for too much.

I wouldn't mind to run this on my own android phone to avoid abusing of your website. I'm not a developer but I guess I could figure out how to make such thing by my own.

**Comment by gadenbuie** [comment]
Thanks for the suggestion. I've been thinking about some updates and the pause feature sounds like a good fit. I'll give the negative time some thought, but I'm less sure about that.

And please feel free to use the online app or the package as much as you like. In either case all the work is done in your browser so my web server isn't doing much work at all 😅

**Comment by moshpirit** [comment]
This is great! Thanks a lot! If I decide to run it on my old phone and implement the negative time would you mind if I contact you to modify this last thing? 😅

**Comment by gadenbuie** [comment]
This is was all done in the latest release of countdown!

**Comment by gadenbuie** [comment]
well, except for the negative counting, I decided not to implement that feature. Sorry!
