### ISSUE TITLE
Broken link to the online timer

### ISSUE THREAD

**Issue by spcanelon** [gadenbuie/countdown#18]
👋 Hi Garrick, just a heads up that the link for the online version of the countdown timer is broken 🙂 

Link: https://apps.garrickadenbuie.com/countdown/

**Comment by gadenbuie** [comment]
Thanks for the heads up! My server ran out of space :cry: but I cleaned out the cobwebs and it should be back up and running.

**Comment by gadenbuie** [comment]
By the way, have you tried `countdown::countdown_fullscreen()`? I use that one a lot when teaching since the timer opens in the RStudio viewer pane. Or you can pop it out into a window or browser.

**Comment by spcanelon** [comment]
Not yet, but I've been meaning to! The fullscreen timer as well as the little one for slides. Today I was in a bit of a time pinch in a non-R tutoring thing (i.e. I didn't have RStudio open) and remembered you had an online version 🙂 

Thanks for the quick fix! ⚙️ 
(and that's too bad about your server 😞)
