### ISSUE TITLE
countdown timer showing up as html div blocks

### ISSUE THREAD

**Issue by jhelvy** [gadenbuie/countdown#20]
Not sure why this started happening, but my timers are now showing up as div blocks. 

![countdown_screenshot](https://user-images.githubusercontent.com/9012994/106675331-f70e5e80-6582-11eb-8f46-4cf1a14d4d68.png)

Here's the code I rendered:

````
---
title: "Testing countdown"
date: February 2, 2021
output: xaringan::moon_reader
---

```{r setup, include=FALSE}
library(countdown)
```

---
class: inverse

```{r, echo=FALSE}
countdown::countdown(minutes = 10,
          top = 0,
          right = 0,
          font_size = '2em')
```

# Here's a 10 minute timer
````

**Comment by gadenbuie** [comment]
It's due to recently updated `rmarkdown`, check out [this comment for a workaround](https://github.com/yihui/xaringan/issues/293#issuecomment-761973964), or you can update to the latest (dev) xaringan.
