### ISSUE TITLE
Can't install from CRAN or Github

### ISSUE THREAD

**Issue by rtheodoro** [gadenbuie/countdown#24]
This is  very nice package, thanks a lot!

I have been trying to add a timer in my `xaringan` presentation and this package is very useful.

I needed to download and use `install_local()`.

Installing from Github:

```r
>devtools::install_github("gadenbuie/countdown")
Using github PAT from envvar GITHUB_PAT
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 57/60
  Rate limit reset at: 2021-12-04 00:21:46 UTC
```

Installing from CRAN
```r
> install.packages("countdown")
Installing package into ‘/home/rtheodoro/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘countdown’ is not available for this version of R
```

**Comment by gadenbuie** [comment]
It looks like maybe there's an issue with your GitHub token (the bad credentials error)?

countdown isn't on CRAN but my packages are available at gadenbuie.r-universe.dev

```
# Enable my universe
options(repos = c(
    gadenbuie = 'https://gadenbuie.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

install.packages('countdown')
```

**Comment by rtheodoro** [comment]
I thought  the problem was my credentials, but I use it today to download and update other projects. I will check it anyway.

Oh, sorry! I thought it was the same package on CRAN. I added yours now! 

Thanks!
