### ISSUE TITLE
quarto port?

### ISSUE THREAD

**Issue by andrewpbray** [gadenbuie/countdown#32]
Hello! I'm an avid user of this package in my xaringan / quarto slides and I was wondering: do you have any plans to port the package to quarto, say via a shortcode? I'm just wondering whether I should put it on my list of projects-to-tinker-with over the coming months.

Thanks for the package!

**Comment by gadenbuie** [comment]
Yes I do! 😄 https://github.com/gadenbuie/countdown/issues/27#issue-1339663831

**Comment by gadenbuie** [comment]
Oops, sent too soon, I meant to say thanks for asking and glad to hear that the package is helpful to you!
