### ISSUE TITLE
Custom sound not working

### ISSUE THREAD

**Issue by jannismain** [gadenbuie/countdown#38]
When providing `play_sound=TRUE` the builtin sound is playing just fine. However, when setting a custom url, the `play_sound` attribute is always cast to `false`

https://github.com/gadenbuie/countdown/blob/260812ee2ee75a330355c742b30ef8ed8bbb022b/inst/countdown/countdown.js#L27C4-L27C55

**Comment by gadenbuie** [comment]
Thanks for the report! This should be fixed now in the dev version of countdown
