### ISSUE TITLE
`countdown_fullscreen()` does not pass on parameters to `countdown()`

### ISSUE THREAD

**Issue by coatless** [gadenbuie/countdown#43]
Two parameters:

- `class`

https://github.com/gadenbuie/countdown/blob/b000d84aed4285d2cea79be2a1e566f28ab6b3f0/r/R/countdown.R#L300

- `start_immediately`

https://github.com/gadenbuie/countdown/blob/b000d84aed4285d2cea79be2a1e566f28ab6b3f0/r/R/countdown.R#L306

Should these be switched to using the function parameters or should the parameters be removed?

**Comment by gadenbuie** [comment]
Yeah, these are just an oversight and we should be passing the function params through:

```patch
- class = c("countdown-fullscreen", NULL),
+ class = c("countdown-fullscreen", class), 
```

```patch
-  start_immediately = FALSE
+  start_immediately = start_immediately
```
