### ISSUE TITLE
Sharing `lib` assets

### ISSUE THREAD

**Issue by coatless** [gadenbuie/countdown#50]
As we've moved to a mono-repo for the different variants, we need to replicate the `lib` folder to each subfolder (`inst/`, `_extensions/countdown/assets`, `src/assets`). 

Probably a short bash script to copy if changes are detected in `lib` or just a script for when a release is scheduled to make sure the `lib` assets are up-to date in the relevant area.

**Comment by gadenbuie** [comment]
I'd like to use `make` for this. We could have a target like `make sync-all` that would update the dependencies in the R, Python and Quarto packages, composed of individual `sync-r`, `sync-python` and `sync-quarto` targets.

Similarly, we'd use the to `make docs` or `make test` or `make release`, etc. as the need arises.

**Comment by coatless** [comment]
Sounds good. I'll implement the `sync` command first. 

Given the `sync` example, I think we're going `action-language` in generating the recipes. So, I'll also add a call to `docs-r` to trigger `pkgdown::build_site()`.  

Could we avoid adding the `-all` and get by `sync`? Or is being more verbose better?
